#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--wd" ]]; then
	close_dash && libreoffice &

elif [[ "$1" == "--gm" ]]; then
        close_dash && firefox gmail.google.com &

elif [[ "$1" == "--sp" ]]; then
	close_dash && spotify &
elif [[ "$1" == "--nd" ]]; then
        close_dash && eww open --toggle nord &
elif [[ "$1" == "--tm" ]]; then
	close_dash && alacritty --working-directory ~ &

elif [[ "$1" == "--th" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--nt" ]]; then
	close_dash && nitrogen &

elif [[ "$1" == "--td" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--vb" ]]; then
	close_dash && virtualbox &

fi
